import pytest
from tachycardia import is_tachycardic


@pytest.mark.parametrize("stringToCheck, expected", [
                        ("tachycardic", True),
                        ("tachycardiC", True),
                        ("TachycardiC", True),
                        ("TACHYCARDIC", True),
                        ("tachycardiC", True),
                        (" tachycardic", True),
                        ("tachycardic ", True),
                        (" tachycardic ", True),
                        ("tachycardic!!!", True),
                        ("!!!tachycardic", True),
                        (" tachycardic!!!", True),
                        ("!!!tachycardic ", True),
                        ("!!!tachycardic!!!", True),
                        ("tachycardic3", True),
                        ("3tachycardic", True),
                        ("Ztachycardic", True),
                        ("tachycardicZ", True),
                        ("3achycardic", True),
                        ("tachycardi3", True),
                        ("achycardic", True), # one letter missing
                        ("tchycardic", True),
                        ("tahycardic", True),
                        ("tacycardic", True),
                        ("tachcardic", True),
                        ("tachyardic", True),
                        ("tachycrdic", True),
                        ("tachycadic", True),
                        ("tachycaric", True),
                        ("tachycardc", True),
                        ("tachycardi", True),
                        ("chycardic", True), # two letters missing
                        ("ahycardic", True),
                        ("acycardic", True),
                        ("achcardic", True),
                        ("achyardic", True),
                        ("achycrdic", True),
                        ("achycadic", True),
                        ("achycaric", True),
                        ("achycardc", True),
                        ("achycardi", True),
                        ("thycardic", True),
                        ("tcycardic", True),
                        ("tchcardic", True),
                        ("tchyardic", True),
                        ("tchycrdic", True),
                        ("tchycadic", True),
                        ("tchycaric", True),
                        ("tchycardc", True),
                        ("tchycardi", True),
                        ("taycardic", True),
                        ("tahcardic", True),
                        ("tahyardic", True),
                        ("tahycrdic", True),
                        ("tahycadic", True),
                        ("tahycaric", True),
                        ("tahycardc", True),
                        ("tahycardi", True),
                        ("taccardic", True),
                        ("tacyardic", True),
                        ("tacycrdic", True),
                        ("tacycadic", True),
                        ("tacycaric", True),
                        ("tacycardc", True),
                        ("tacycardi", True),
                        ("tachardic", True),
                        ("tachcrdic", True),
                        ("tachcadic", True),
                        ("tachcaric", True),
                        ("tachcardc", True),
                        ("tachcardi", True),
                        ("tachyrdic", True),
                        ("tachyadic", True),
                        ("tachyaric", True),
                        ("tachyardc", True),
                        ("tachyardi", True),
                        ("tachycdic", True),
                        ("tachycric", True),
                        ("tachycrdc", True),
                        ("tachycrdi", True),
                        ("tachycaic", True),
                        ("tachycadc", True),
                        ("tachycadi", True),
                        ("tachycarc", True),
                        ("tachycari", True),
                        ("tachycard", True),
                        ("hycardic", False), # three letters missing
                        ("achcaric", False),
                        ("tachycar", False),
                        ("chycardi", False),
                        ("achycard", False),
                        ("tacardic", False),
                        ("tacycaic", False),
                        ("tachy3cardic", False),
                        ("tachyZcardic", False),
                        ])
def test_is_tachycardic(stringToCheck, expected):
    result = is_tachycardic(stringToCheck)
    assert result is expected
